# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: requirements-txt-fixer
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-xml
    -   id: check-ast
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0  # Use the ref you want to point at
    hooks:
    -   id: python-use-type-annotations
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
    - id: bandit
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    - id: isort
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
    - id: pycln
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.2
    hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_trivy
    - id: terraform_tflint
    - id: terraform_checkov